import { StyleSheet, Dimensions } from 'react-native';

const DEVICE_WIDTH = Dimensions.get('window').width;
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollViewContainer: {
    backgroundColor: '#fff',
  },
  textContainer: {
    width: '70%',
  },
  text: {
    fontSize: 16,
    color: '#75787b', // Zippity gray
    textAlign: 'center',
  },
  item: {
    backgroundColor: '#ffffff',
    padding: 15,
    marginVertical: 3,
    marginHorizontal: 16,
    borderWidth: 0.5,
    borderColor: '#e69391',
    borderRadius: 3,
  },
  selectedItem: {
    backgroundColor: '#48999e',
    padding: 15,
    marginVertical: 3,
    marginHorizontal: 16,
    borderWidth: 0.5,
    borderColor: '#ccc',
    borderRadius: 3,
    color: '#fff',
  },
  title: {
    fontSize: 22,
    color: '#262626',
  },
  selectedTitle: {
    color: '#fff',
    fontSize: 22,
  },
  markerStyle: {
    borderColor: '#459ba1',
    backgroundColor: 'white',
  },
  selectedStyle: {
    backgroundColor: '#459ba1',
  },
  buttonText: {
    fontSize: 24,
    color: '#9f9f9f',
  },
  button: {
    marginTop: 40,
    width: 200,
    height: 50,
    borderRadius: 5,
    justifyContent: 'center',
    backgroundColor: '#dfdfdf',
    marginBottom: 20,
    textAlign: 'center',
    display: 'flex',
  },
  buttonCenter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  textActive: {
    color: '#fff',
    fontSize: 24,
  },
  iconActive: {
    color: '#fff',
    fontSize: 20,
  },
  selectedButton: {
    marginTop: 30,
    width: 200,
    height: 50,
    borderRadius: 5,
    justifyContent: 'center',
    backgroundColor: '#48999e',
  },
  infoContainer: {
    backgroundColor: '#e5e8e8',
    height: 260,
    width: DEVICE_WIDTH - 30,
    marginTop: 3,
    borderRadius: 10,
  },
  inforContainerView: {
    alignItems: 'center',
  },
  scheduleTitleText: {
    fontSize: 36,
    fontWeight: '600',
    color: '#262626',
    textAlign: 'center',
    margin: 10,
  },
  optionText: {
    fontSize: 20,
    fontWeight: '400',
    color: '#000000',
    textAlign: 'center',
  },
  scheduleText: {
    fontSize: 20,
    fontWeight: '400',
    color: '#ffffff',
    textAlign: 'center',
    width: DEVICE_WIDTH - 90,
  },
  optionView: {
    display: 'flex',
    flexDirection: 'row',
    margin: 5,
  },
  optionIcon: {
    width: 20,
    height: 20,
    marginRight: 5,
  },
  scheduleView: {
    backgroundColor: '#459ba1',
    width: DEVICE_WIDTH - 90,
    height: 40,
    margin: 5,
    borderRadius: 10,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },
  infoLabel: {
    fontSize: 20,
    fontWeight: '500',
    textAlign: 'left',
    marginTop: 20,
    marginLeft: 10,
    color: '#262626',
  },
  formContainer: {
    backgroundColor: '#ffffff',
    height: 1300,
    width: DEVICE_WIDTH - 30,
    marginTop: -30,
    borderRadius: 10,
    padding: 10,
    borderWidth: 0.5,
    borderColor: '#d6d7da',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  chooseText: {
    fontSize: 36,
    fontWeight: '600',
    color: '#262626',
    textAlign: 'left',
    margin: 15,
    marginTop: 30,
  },
  chooseTimeText: {
    fontSize: 26,
    fontWeight: '500',
    textAlign: 'left',
    marginTop: 20,
    color: '#262626',
  },
  sliderContainer: {
    display: 'flex',
    flexDirection: 'row',
    marginLeft: 15,
  },
  timeInfoContainer: {
    display: 'flex',
    flexDirection: 'row',
    marginLeft: 60,
    marginRight: 60,
    marginTop: 20,
  },
  timeInfoBox: {
    borderColor: '#dfdfdf',
    borderWidth: 1,
    borderRadius: 10,
    width: 100,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeInfoText: {
    fontSize: 20,
    fontWeight: '400',
    color: '#818181',
  },
  timeInfoTo: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textArea: {
    height: 120,
    borderColor: '#dfdfdf',
    borderRadius: 3,
    borderWidth: 1,
    marginTop: 5,
    fontSize: 15,
  },
  errorText: {
    fontSize: 20,
    fontWeight: '400',
    color: '#d95654',
    marginBottom: 30,
    lineHeight: 30,
  },
  flatList: {
    flexGrow: 0,
    height: 320,
  },
  commentsView: {
    paddingTop: 80,
  },
  commentsText: {
    fontSize: 20,
    fontWeight: '400',
    color: '#262626',
  },
  nextIcon: {
    fontSize: 20,
    color: '#a0a0a0',
  },
});
